@extends('layouts.master')

@section('content')
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
    here's the content of home!!<br>
@stop